BookComrade/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using BookComrade.Data;
using BookComrade.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VersOne.Epub;
using HtmlAgilityPack;

namespace BookComrade.Controllers
{
    [Authorize(Roles = "admin, standardUser, premiumUser")]
    public class LibraryController : Controller
    {

        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;
        private readonly AppDbContext context;

        public LibraryController(
            AppDbContext context,
            RoleManager<IdentityRole> roleManager,
            UserManager<IdentityUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.context = context;
        }

        public IActionResult Index()
        {
            return User.IsInRole("standardUser")? View(context.Books.Where(x=>!x.IsPremium)) : View(context.Books);
        }

        public IActionResult Book()
        {
            var bookId = int.Parse(Request.Query["bookId"]);
            var book = context.Books.Find(bookId);
            if (User.IsInRole("standardUser") && book.IsPremium)
                return NotFound();
            var reviews = context.Reviews.Where(x => x.BookId == bookId);

            return View(new BookReview(){Book = book, Review = new Review(), Reviews = reviews});
        }

        public IActionResult Category()
        {
            var category = Enum.Parse(typeof(CategoryEnum),Request.Query["category"]);
            var books = User.IsInRole("standardUser") ? context.Books.Where(x => !x.IsPremium) : context.Books;
            return View(books.Where(book=>book.Category.Equals(category)));
        }
        
        public IActionResult Navigation()
        {
            var bookId = int.Parse(Request.Query["bookId"]);
            var book = context.Books.Find(bookId);
            using (EpubBookRef bookRef = EpubReader.OpenBook(book.Path))
                return View(Tuple.Create(bookRef.GetNavigation(), bookId));
            
        }
        public IActionResult ReadSection()
        {
            var bookId = int.Parse(Request.Query["bookId"]);
            var chapterName = (Request.Query["chapterName"]);
            var book = context.Books.Find(bookId);
            using (EpubBookRef bookRef = EpubReader.OpenBook(book.Path))
            {
                var chapter = bookRef.GetNavigation().Where(n => n.Title.Equals(chapterName)).First();
                var text = PrintTextContentFile(chapter.HtmlContentFileRef.ReadContent());
                ViewBag.HtmlStr = text;
                return View();
            }
          
        }
        private string PrintTextContentFile(String textContentFile)
        {
            HtmlDocument htmlDocument = new HtmlDocument();
            htmlDocument.LoadHtml(textContentFile);
            StringBuilder sb = new StringBuilder();
            foreach (HtmlNode node in htmlDocument.DocumentNode.SelectNodes("//text()"))
                sb.AppendLine(node.InnerText.Trim());
            return sb.ToString();
}
    }
}

BookComrade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>@ViewData["Title"] - BookComrade</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" 
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookComrade</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Страница администратора</a>
                                }
                            }
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="Index">Библиотека</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Book">Скачать</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <form class="form-inline" asp-controller="Home" asp-action="Search" method="get">
                                <i class="fas fa-search" aria-hidden="true" style="margin-right: 5px;"></i>
                                <div class="md-form my-0">
                                    <input class="form-control mr-sm-2" type="text" name="search" placeholder="Поиск"/>
                                </div>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BookComrade - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>